### ISSUE TITLE
In 1001 Fonts, the capital Eng is missing.

### ISSUE THREAD

**Issue by prakashDiana** [cssobral2013/Bertioga-Sans#1]
The capital Eng had some problems in the upright styles, and now it is only in the italic styles.

![Screenshot_20240315-201015](https://github.com/cssobral2013/Bertioga-Sans/assets/163605970/9a9fb8a6-fc1f-45ba-9c3d-4f763d897a57)

**Comment by prakashDiana** [comment]
It says:

> ### Bertioga Sans
>Is developed from Arimo and Libra Sans. Main changes include:
>
>• Expanding to 7 weights plus matching italics;
>• Non-serifed 'J';
>• Changed capital Eng to N-shaped;
>• Imported BGR Cyrillic from Libra Sans.
>

**Comment by cssobral2013** [comment]
This has been fixed in update v3.5(2).
